//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_UOS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN2K8SVR;Initial Catalog=ERP_UOS;User ID=appsuser;Password=abcbook")]
        public string ERP_UOSConnectionString1 {
            get {
                return ((string)(this["ERP_UOSConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN2K8SVR;Initial Catalog=NizamiBrothers;User ID=appsuser")]
        public string NizamiBrothersConnectionString {
            get {
                return ((string)(this["NizamiBrothersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHOAIBPC;Initial Catalog=NizamiBrothers;Persist Security Info=True;Us" +
            "er ID=appsuser;Password=abcbook")]
        public string NizamiBrothersConnectionString1 {
            get {
                return ((string)(this["NizamiBrothersConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN2K8SVR;Initial Catalog=NizamiBrothers;Persist Security Info=True;U" +
            "ser ID=appsuser;Password=abcbook")]
        public string ERP_UOSConnectionString {
            get {
                return ((string)(this["ERP_UOSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHOAIBPC\\SQL2008;Initial Catalog=NizamiBrothers;Persist Security Info" +
            "=True;User ID=sa;Password=smc786")]
        public string NizamiBrothersConnectionString2 {
            get {
                return ((string)(this["NizamiBrothersConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN2K8SVR;Initial Catalog=NizamiBrothers;User ID=sa;Password=abcbook1" +
            "23$%^")]
        public string NizamiBrothersConnectionString3 {
            get {
                return ((string)(this["NizamiBrothersConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHOAIBSIDDIQUI\\SQL2008;Initial Catalog=ERP_UOS;User ID=sa;Password=sm" +
            "c786")]
        public string ERP_UOSConnectionString2 {
            get {
                return ((string)(this["ERP_UOSConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=ERP_UOS;User ID=sa")]
        public string ERP_UOSLocal {
            get {
                return ((string)(this["ERP_UOSLocal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.188;Initial Catalog=ERP_UOS;User ID=sa;Password=smc786")]
        public string ERP_UOSConnectionString3 {
            get {
                return ((string)(this["ERP_UOSConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KomfitLenovo;Initial Catalog=ERP_UOS;Persist Security Info=True;User " +
            "ID=sa;Password=smc786")]
        public string ERP_UOSConnectionString4 {
            get {
                return ((string)(this["ERP_UOSConnectionString4"]));
            }
        }
    }
}
